import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:notes_gallery/utils/give_exception.dart';

class Authentication with ChangeNotifier {
  String? _token;
  String? _userId;
  DateTime? _expiryDate;
  String _status = '';

  bool get isAuth {
    return token != null;
  }

  String? get token {
    if (_expiryDate != null &&
        _expiryDate!.isAfter(DateTime.now()) &&
        _token != null) {
      return _token;
    }
    return null;
  }

  String? get status {
    return _status;
  }

  String? get userId {
    return _userId;
  }

  // String get userId {
  //   return _userId;
  // }
  //f
  Future<String?> signIn(
    String email,
    String password,
  ) async {
    final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
    try {
      UserCredential user = await _firebaseAuth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
      print(" USER user detail-:  ${user.user}");
      IdTokenResult? idTokenResult = await user.user?.getIdTokenResult(true);
      print(" User user-> result  ${idTokenResult!.claims!['user_id']}");
      _userId = idTokenResult.claims?['user_id'] ?? "";
      _status = "successful";
      notifyListeners();

      return status;
    } on FirebaseAuthException catch (e) {
      _status = AuthExceptionHandler.handleException(e);
      notifyListeners();

      return status;
    }
  }

  Future<String?> _authenticate(
      String email, String password, String urlSegment) async {
    String? url = 'https://protected-waters-32301.herokuapp.com/signup';
    //this both are generated by firebase

    try {
      final response = await http.post(Uri.parse(url),
          headers: <String, String>{
            'Content-Type': 'application/json',
          },
          body: json.encode({
            'email': email,
            'password': password,
          }),
          encoding: Encoding.getByName('utf-8'));

      final responseData = json.decode(response.body);

      print(responseData);
      print('\n\n\n\n\n');
      //if response data is not null ie it has get values do this\

      return signIn(email, password);
    } catch (error) {
      print(error);
      print('\n\n\n\n\n');
      return "failed";
    }
  }

  Future<String?> signUp(String? email, String? password) async {
    return _authenticate(email!, password!, 'signUp');
  }

  // Future<void> signIn(String? email, String? password) async {
  //   return _authenticate(email!, password!, 'signInWithPassword');
  // }
}
